## Chargement des données
Toutes les tables proviennent de https://www.data.gouv.fr/

# Chargement de la table "sujet_tele"
Cette table est expose le temps de diffusion par chaîne de différentes thématiques

In [3]:
import requests
url_sujet_tele = "https://static.data.gouv.fr/resources/classement-thematique-des-sujets-de-journaux-televises-janvier-2000-decembre-2020/20241015-124725/ina-barometre-jt-tv-donnees-quotidiennes-2000-2020-nbre-sujets-durees-202410.csv"
requests.get(url_sujet_tele)
# Vérification que l'url fonctionne

In [4]:
import pandas as pd

req = requests.get(url_sujet_tele)
print(req.content[:20])
# Observe le format des données

b'02/01/2000;France 3;'

In [5]:
# Définission du nom des colonnes
colonnes = ["Date", "Chaîne","Vide", "Thématique", "Nb_sujets", "Duree_sec"]

In [6]:
with open('temp.csv', 'w', encoding='latin-1') as f:
    f.write(req.text)
sujet_tele = pd.read_csv('temp.csv', sep=';', encoding='latin-1', header=None, names=colonnes) 
# latin permet d'encoder les accents

In [7]:
sujet_tele.head()

         Date    Chaîne  Vide       Thématique  Nb_sujets  Duree_sec
0  02/01/2000  France 3   NaN     Catastrophes          2        235
1  02/01/2000  France 3   NaN  Culture-loisirs          1        138
2  02/01/2000  France 3   NaN    Environnement          3        306
3  02/01/2000  France 3   NaN    International          2        241
4  02/01/2000  France 3   NaN          Société          2        160

In [8]:
sujet_tele["Thématique"].unique()

array(['Catastrophes', 'Culture-loisirs', 'Environnement',
       'International', 'Société', 'Sport', 'Economie', 'Education',
       'Politique France', 'Santé', 'Histoire-hommages', 'Justice',
       'Faits divers', 'Sciences et techniques'], dtype=object)

In [9]:
# Vérification que la colonne "Vide" ne contient pas de valeurs non nulles
sujet_tele['Vide'].notna().any()

np.False_

In [10]:
# Supprime la colonne "Vide"
sujet_tele = sujet_tele.drop(columns=['Vide'])
sujet_tele.head()

         Date    Chaîne       Thématique  Nb_sujets  Duree_sec
0  02/01/2000  France 3     Catastrophes          2        235
1  02/01/2000  France 3  Culture-loisirs          1        138
2  02/01/2000  France 3    Environnement          3        306
3  02/01/2000  France 3    International          2        241
4  02/01/2000  France 3          Société          2        160

# Chargement de la table "audience"

In [11]:
# Vérification du fonctionnement de l'url
url_audience = "http://www.cnc.fr/c/document_library/get_file?uuid=ac00e68f-871d-4129-ba90-977c84484bdd&groupId=18"
requests.get(url_audience)

In [12]:
req = requests.get(url_audience)
with open('temp.xlsx', 'wb') as f:
    f.write(req.content)
audience = pd.read_excel('temp.xlsx', sheet_name='PartdAudience')

In [13]:
audience.head(10)
# La mise en page du excel s'étale sur 4 lignes que nous allons supprimer

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,"Retour au menu ""Audience de la télévision""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Parts d'audience des chaînes de télévision* (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,TF1,France 2,France 3,Canal+,La 5,France 5,M6,Arte,C8,...,Gulli,France Ô,TF1 séries films,L'Equipe,6ter,RMC Story,RMC Découverte,Chérie 25,LCI,Franceinfo
6,1989,41,23.4,10.3,4.4,13,-,6.4,-,-,...,-,-,-,-,-,-,-,-,-,-
7,1990,41.9,22.1,11,4.3,11.7,-,7.3,-,-,...,-,-,-,-,-,-,-,-,-,-
8,1991,42.1,21.3,11.3,4.6,10.9,-,8,-,-,...,-,-,-,-,-,-,-,-,-,-
9,1992,41,24,13.6,5,ns,-,10.2,-,-,...,-,-,-,-,-,-,-,-,-,-

In [14]:
audience = pd.read_excel('temp.xlsx',
                         sheet_name='PartdAudience',
                         skiprows=5,
                         header = 1
                        )

In [15]:
audience = audience.rename(columns={audience.columns[0]: 'Annee'})

In [16]:
audience.head()

,Annee,TF1,France 2,France 3,Canal+,La 5,France 5,M6,Arte,C8,...,Gulli,France Ô,TF1 séries films,L'Equipe,6ter,RMC Story,RMC Découverte,Chérie 25,LCI,Franceinfo
0,1989,41.0,23.4,10.3,4.4,13,-,6.4,-,-,...,-,-,-,-,-,-,-,-,-,-
1,1990,41.9,22.1,11.0,4.3,11.7,-,7.3,-,-,...,-,-,-,-,-,-,-,-,-,-
2,1991,42.1,21.3,11.3,4.6,10.9,-,8.0,-,-,...,-,-,-,-,-,-,-,-,-,-
3,1992,41.0,24.0,13.6,5.0,ns,-,10.2,-,-,...,-,-,-,-,-,-,-,-,-,-
4,1993,41.0,24.7,14.6,4.9,-,-,11.2,0.9,-,...,-,-,-,-,-,-,-,-,-,-

In [19]:
audience.columns

Index(['Annee', 'TF1', 'France 2', 'France 3', 'Canal+', 'La 5', 'France 5',
       'M6 ', 'Arte', 'C8', 'W9', 'TMC', 'TFX', 'NRJ12', 'France 4', 'BFMTV',
       'CNews', 'CStar', 'Gulli', 'France Ô', 'TF1 séries films', 'L'Equipe',
       '6ter', 'RMC Story', 'RMC Découverte', 'Chérie 25', 'LCI',
       'Franceinfo'],
      dtype='object')

In [37]:
audience.columns[(audience.columns.isin(sujet_tele["Chaîne"].unique()))
                 | (audience.columns.isin(['Annee']))]

Index(['TF1', 'France 2', 'France 3', 'Arte'], dtype='object')

In [ ]:
mask = audience.columns.isin(sujet_tele["Chaîne"].unique()) | audience.columns.isin(['Annee'])
audience = audience.loc[:, mask]
audience.head()

TypeError: unsupported operand type(s) for &: 'str' and 'bool'

# Chargement de la base "parite"

In [ ]:
url_parite = "https://static.data.gouv.fr/resources/temps-de-parole-des-hommes-et-des-femmes-a-la-television-et-a-la-radio/20190312-191033/20190308-stats.csv"

requests.get(url_parite)

In [ ]:
req = requests.get(url_parite)
print(req.content[:20])

b'media_type,channel_c'

In [ ]:
with open('temp.csv', 'w', encoding='utf-8') as f:
    f.write(req.text.encode('latin-1').decode('utf-8'))
parite = pd.read_csv('temp.csv', sep=',', encoding='utf-8', header=0) 
# double encodage pour corriger les problèmes d'accents

In [ ]:
# Ne garde que les chaînes présentent dans sujet_tele
parite = parite[parite['channel_name'].isin(sujet_tele['Chaîne'].unique())]

In [ ]:
parite.head()

,media_type,channel_code,channel_name,is_public_channel,date,week_day,school_holiday_zones,civil_holyday,hour,male_duration,female_duration,music_duration
769393,tv,FR2,France 2,True,2010-01-01,Friday,ABC,True,19,1393.26,445.54,1614.72
769394,tv,FR2,France 2,True,2010-01-01,Friday,ABC,True,22,1774.36,320.26,1427.68
769395,tv,FR2,France 2,True,2010-01-02,Saturday,ABC,False,12,2148.62,609.02,762.86
769396,tv,FR2,France 2,True,2010-01-02,Saturday,ABC,False,16,1561.22,388.66,1276.36
769397,tv,FR2,France 2,True,2010-01-02,Saturday,ABC,False,20,2240.60,725.44,558.02

In [ ]:
# Durée totale des journaux télévisés

Journaux = sujet_tele.groupby(['Date', 'Chaîne']).agg(
    Nombre_sujets = ('Nb_sujets', 'count'),
    Duree = ('Duree_sec', 'sum'),
    ).reset_index()



Journaux.head(50)

          Date    Chaîne  Nombre_sujets  Duree
0   01/01/2000      Arte              6    684
1   01/01/2000  France 2              8   1990
2   01/01/2000  France 3              5   1287
3   01/01/2000        M6              5    821
4   01/01/2000       TF1              5   2139
5   01/01/2001      Arte              5   1329
6   01/01/2001  France 2              6   1912
7   01/01/2001  France 3              6    959
8   01/01/2001        M6              6    624
9   01/01/2001       TF1              6   1966
10  01/01/2002      Arte              5   1158
11  01/01/2002  France 2              6   2273
12  01/01/2002  France 3              4   1261
13  01/01/2002        M6              5    743
14  01/01/2002       TF1              7   2059
15  01/01/2003      Arte              5    939
16  01/01/2003  France 2              7   2043
17  01/01/2003  France 3              8   1406
18  01/01/2003        M6              5    568
19  01/01/2003       TF1              6   2051
20  01/01/2004      Arte              7   1138
21  01/01/2004  France 2             10   2185
22  01/01/2004  France 3              7   1325
23  01/01/2004        M6              5    463
24  01/01/2004       TF1              8   1927
25  01/01/2005      Arte              4    389
26  01/01/2005  France 2              4   1828
27  01/01/2005  France 3              4   1314
28  01/01/2005        M6              6    708
29  01/01/2005       TF1              5   2166
30  01/01/2006      Arte              4    675
31  01/01/2006  France 2              5   1616
32  01/01/2006  France 3              7   1761
33  01/01/2006        M6              7    583
34  01/01/2006       TF1              9   1810
35  01/01/2007      Arte              4    739
36  01/01/2007  France 2              7   1759
37  01/01/2007  France 3              7   1244
38  01/01/2007        M6              3    630
39  01/01/2007       TF1              8   1878
40  01/01/2008      Arte              4    631
41  01/01/2008  France 2              7   1560
42  01/01/2008  France 3              6   1286
43  01/01/2008        M6              5    613
44  01/01/2008       TF1              7   1821
45  01/01/2009      Arte              3    762
46  01/01/2009  France 2              8   1744
47  01/01/2009  France 3              6   1356
48  01/01/2009        M6              6    693
49  01/01/2009       TF1              7   1820