## Chargement des données
Toutes les tables proviennent de https://www.data.gouv.fr/

# Chargement de la table "sujet_tele"
Cette table est expose le temps de diffusion par chaîne de différentes thématiques

In [67]:
import requests
url_sujet_tele = "https://static.data.gouv.fr/resources/classement-thematique-des-sujets-de-journaux-televises-janvier-2000-decembre-2020/20241015-124725/ina-barometre-jt-tv-donnees-quotidiennes-2000-2020-nbre-sujets-durees-202410.csv"
requests.get(url_sujet_tele)
# Vérification que l'url fonctionne

In [68]:
import pandas as pd

req = requests.get(url_sujet_tele)
print(req.content[:20])
# Observe le format des données

b'02/01/2000;France 3;'

In [69]:
# Définission du nom des colonnes
colonnes = ["Date", "Chaîne","Vide", "Thématique", "Nb_sujets", "Duree_sec"]

In [70]:
with open('temp.csv', 'w', encoding='latin-1') as f:
    f.write(req.text)
sujet_tele = pd.read_csv('temp.csv', sep=';', encoding='latin-1', header=None, names=colonnes) 
# latin permet d'encoder les accents

In [71]:
sujet_tele.head()

         Date    Chaîne  Vide       Thématique  Nb_sujets  Duree_sec
0  02/01/2000  France 3   NaN     Catastrophes          2        235
1  02/01/2000  France 3   NaN  Culture-loisirs          1        138
2  02/01/2000  France 3   NaN    Environnement          3        306
3  02/01/2000  France 3   NaN    International          2        241
4  02/01/2000  France 3   NaN          Société          2        160

In [72]:
sujet_tele["Thématique"].unique()

array(['Catastrophes', 'Culture-loisirs', 'Environnement',
       'International', 'Société', 'Sport', 'Economie', 'Education',
       'Politique France', 'Santé', 'Histoire-hommages', 'Justice',
       'Faits divers', 'Sciences et techniques'], dtype=object)

In [73]:
# Vérification que la colonne "Vide" ne contient pas de valeurs non nulles
sujet_tele['Vide'].notna().any()

np.False_

In [74]:
# Supprime la colonne "Vide"
sujet_tele = sujet_tele.drop(columns=['Vide'])
sujet_tele.head()

         Date    Chaîne       Thématique  Nb_sujets  Duree_sec
0  02/01/2000  France 3     Catastrophes          2        235
1  02/01/2000  France 3  Culture-loisirs          1        138
2  02/01/2000  France 3    Environnement          3        306
3  02/01/2000  France 3    International          2        241
4  02/01/2000  France 3          Société          2        160

# Chargement de la table "audience"

In [75]:
# Vérification du fonctionnement de l'url
url_audience = "http://www.cnc.fr/c/document_library/get_file?uuid=ac00e68f-871d-4129-ba90-977c84484bdd&groupId=18"
requests.get(url_audience)

In [76]:
req = requests.get(url_audience)
with open('temp.xlsx', 'wb') as f:
    f.write(req.content)
audience = pd.read_excel('temp.xlsx', sheet_name='PartdAudience')

In [ ]:
audience.head(10)
# La mise en page du excel s'étale sur 4 lignes que nous allons supprimer

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,"Retour au menu ""Audience de la télévision""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Parts d'audience des chaînes de télévision* (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,TF1,France 2,France 3,Canal+,La 5,France 5,M6,Arte,C8,...,Gulli,France Ô,TF1 séries films,L'Equipe,6ter,RMC Story,RMC Découverte,Chérie 25,LCI,Franceinfo
6,1989,41,23.4,10.3,4.4,13,-,6.4,-,-,...,-,-,-,-,-,-,-,-,-,-
7,1990,41.9,22.1,11,4.3,11.7,-,7.3,-,-,...,-,-,-,-,-,-,-,-,-,-
8,1991,42.1,21.3,11.3,4.6,10.9,-,8,-,-,...,-,-,-,-,-,-,-,-,-,-
9,1992,41,24,13.6,5,ns,-,10.2,-,-,...,-,-,-,-,-,-,-,-,-,-

In [92]:
audience = pd.read_excel('temp.xlsx',
                         sheet_name='PartdAudience',
                         skiprows=5,
                         header = 1
                        )

In [104]:
audience = audience.rename(columns={audience.columns[0]: 'Annee'})

In [105]:
audience.head()

,Annee,TF1,France 2,France 3,Canal+,La 5,France 5,M6,Arte,C8,...,Gulli,France Ô,TF1 séries films,L'Equipe,6ter,RMC Story,RMC Découverte,Chérie 25,LCI,Franceinfo
0,1989,41.0,23.4,10.3,4.4,13,-,6.4,-,-,...,-,-,-,-,-,-,-,-,-,-
1,1990,41.9,22.1,11.0,4.3,11.7,-,7.3,-,-,...,-,-,-,-,-,-,-,-,-,-
2,1991,42.1,21.3,11.3,4.6,10.9,-,8.0,-,-,...,-,-,-,-,-,-,-,-,-,-
3,1992,41.0,24.0,13.6,5.0,ns,-,10.2,-,-,...,-,-,-,-,-,-,-,-,-,-
4,1993,41.0,24.7,14.6,4.9,-,-,11.2,0.9,-,...,-,-,-,-,-,-,-,-,-,-

# Chargement de la base "parite"

In [107]:
url_parite = "https://static.data.gouv.fr/resources/temps-de-parole-des-hommes-et-des-femmes-a-la-television-et-a-la-radio/20190312-191033/20190308-stats.csv"

requests.get(url_parite)

In [109]:
req = requests.get(url_parite)
print(req.content[:20])

b'media_type,channel_c'

In [123]:
with open('temp.csv', 'w', encoding='utf-8') as f:
    f.write(req.text.encode('latin-1').decode('utf-8'))
parite = pd.read_csv('temp.csv', sep=',', encoding='utf-8', header=0) 
# double encodage pour corriger les problèmes d'accents

In [124]:
parite.head()

,media_type,channel_code,channel_name,is_public_channel,date,week_day,school_holiday_zones,civil_holyday,hour,male_duration,female_duration,music_duration
0,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,5,224.34,191.86,3180.34
1,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,11,160.68,137.90,3297.08
2,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,13,124.20,168.28,3303.96
3,radio,CHE,Chérie FM,False,2001-01-01,Monday,ABC,True,18,251.20,185.58,3156.34
4,radio,CHE,Chérie FM,False,2001-01-02,Tuesday,ABC,False,6,550.76,223.60,2818.50